[mypy]
python_version = 3.11
files = data_transformations, tests
ignore_missing_imports = True
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
follow_imports = skip

[mypy-traitlets.*]
ignore_errors = True